# Generated by Django 5.2.7 on 2025-11-05 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome da área')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(default='Da ideia à prática, do campus à carreira.', max_length=200, verbose_name='Título do Banner')),
                ('subtitulo_banner', models.CharField(default='Aprender, se conectar e crescer: seu futuro começa aqui.', max_length=255, verbose_name='Subtítulo do Banner')),
                ('imagem_banner', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('titulo_sobre', models.CharField(default='O que é o LinkIF?', max_length=100, verbose_name='Título da seção Sobre')),
                ('texto_sobre', models.TextField(default='O LinkIF é uma plataforma do IFRN – Campus São Paulo do Potengi que conecta estudantes, ex-alunos e empresas.', verbose_name='Texto da seção Sobre')),
                ('card1_titulo', models.CharField(default='Plataforma Integrada', max_length=100)),
                ('card1_texto', models.TextField(default='Um ambiente digital criado para centralizar estágios e oportunidades profissionais no Potengi.')),
                ('card1_icon', models.ImageField(blank=True, null=True, upload_to='home/icons/')),
                ('card2_titulo', models.CharField(default='Conexão Estratégica', max_length=100)),
                ('card2_texto', models.TextField(default='Coloca em diálogo estudantes e empresas, aproximando o IFRN do mercado de trabalho.')),
                ('card2_icon', models.ImageField(blank=True, null=True, upload_to='home/icons/')),
                ('card3_titulo', models.CharField(default='Porta de entrada', max_length=100)),
                ('card3_texto', models.TextField(default='Mais que um sistema, o LinkIF é o caminho para transformar formação técnica em experiência real.')),
                ('card3_icon', models.ImageField(blank=True, null=True, upload_to='home/icons/')),
                ('titulo_estudantes', models.CharField(default='Para Estudantes', max_length=100)),
                ('texto_estudantes', models.TextField(default='Mostre suas habilidades e encontre oportunidades que combinam com você.')),
                ('imagem_estudantes', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('titulo_empresas', models.CharField(default='Para Empresas', max_length=100)),
                ('texto_empresas', models.TextField(default='Encontre os talentos que fazem a diferença e fortaleça sua equipe com jovens qualificados do IFRN.')),
                ('imagem_empresas', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo da Página Inicial',
                'verbose_name_plural': 'Conteúdos da Página Inicial',
            },
        ),
        migrations.CreateModel(
            name='PerfilFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perfis/logos/')),
                ('cor_titulo', models.CharField(blank=True, default='#1b1f5b', max_length=30, verbose_name='Cor do título (opcional, hex ou nome)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Perfil de Formação',
                'verbose_name_plural': 'Perfis de Formação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='LinkIF', max_length=100, verbose_name='Nome do site')),
                ('descricao_curta', models.TextField(default='Conectando talentos técnicos do IFRN às melhores oportunidades profissionais.', verbose_name='Descrição curta')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('email_contato', models.EmailField(default='contato@ifrn.edu.br', max_length=254, verbose_name='E-mail de contato')),
                ('telefone', models.CharField(default='(84) 98888-8888', max_length=50, verbose_name='Telefone')),
                ('endereco', models.CharField(default='Av. Potengi, São Paulo do Potengi - RN, 59460-000', max_length=255, verbose_name='Endereço')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('mapa_embed', models.TextField(blank=True, help_text='Cole aqui o código embed do Google Maps.', null=True, verbose_name='Mapa (iframe do Google Maps)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='linkif.perfilformacao')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAtuacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='linkif.perfilformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('tipo', models.CharField(choices=[('estagio', 'Estágio'), ('emprego', 'Emprego'), ('bolsa', 'Bolsa')], default='estagio', max_length=20, verbose_name='Tipo')),
                ('remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneração')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=60, verbose_name='Estado')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('encerrada', 'Encerrada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.coordenador')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkif.areaatuacao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem do candidato')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='usuarios.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='linkif.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-data_candidatura'],
                'unique_together': {('vaga', 'aluno')},
            },
        ),
    ]
