# Generated by Django 5.2.7 on 2025-12-05 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Curta')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perfis/logos/')),
                ('cor_titulo', models.CharField(blank=True, default='#1b1f5b', max_length=30, verbose_name='Cor do título')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Perfil de Formação',
                'verbose_name_plural': 'Perfis de Formação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(default='Da ideia à prática, do campus à carreira.', max_length=200)),
                ('subtitulo_banner', models.CharField(default='Aprender, se conectar e crescer: seu futuro começa aqui.', max_length=255)),
                ('imagem_banner', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('nome_site', models.CharField(default='LinkIF', max_length=100, verbose_name='Nome do site')),
                ('descricao_curta', models.TextField(default='Conectando talentos técnicos do IFRN às melhores oportunidades profissionais.')),
                ('email_contato', models.EmailField(default='contato@ifrn.edu.br', max_length=254)),
                ('telefone', models.CharField(default='(84) 98888-8888', max_length=50)),
                ('endereco', models.CharField(default='Av. Potengi, São Paulo do Potengi - RN', max_length=255)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('mapa_embed', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='linkif.perfilformacao')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAtuacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='linkif.perfilformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da vaga')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada da vaga')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('tipo', models.CharField(choices=[('estagio', 'Estágio'), ('emprego', 'Emprego'), ('bolsa', 'Bolsa')], default='estagio', max_length=20, verbose_name='Tipo de vaga')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Modalidade')),
                ('remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneração (R$)')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('encerrada', 'Encerrada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('aprovado_por', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='linkif.perfilformacao', verbose_name='Curso Alvo')),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL, verbose_name='Empresa responsável')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem do candidato')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='linkif.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-data_candidatura'],
                'unique_together': {('vaga', 'aluno')},
            },
        ),
    ]
