# Generated by Django 5.2.7 on 2025-12-10 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linkif', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencia',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='linkif.perfilformacao'),
        ),
        migrations.AddField(
            model_name='areaatuacaoperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='linkif.perfilformacao'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='linkif.perfilformacao', verbose_name='Curso Alvo'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL, verbose_name='Empresa responsável'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='linkif.vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('vaga', 'aluno')},
        ),
    ]
