# Generated by Django 5.2.7 on 2025-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
