# Generated by Django 5.2.7 on 2025-11-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
