# Generated by Django 5.2.7 on 2025-12-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='etapa',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_aprovacao', 'Pendente aprovação'), ('publicada', 'Publicada'), ('inscricoes_fechadas', 'Inscrições fechadas'), ('analise_curriculos', 'Análise de currículos'), ('entrevistas', 'Entrevistas'), ('finalizada', 'Finalizada')], default='pendente_aprovacao', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('analisando', 'Currículo em análise'), ('pre_selecionado', 'Pré-selecionado'), ('entrevista', 'Entrevista agendada'), ('finalista', 'Finalista'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
