# Generated by Django 5.2.7 on 2025-11-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0002_mensagemcontato_remove_siteconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card1_texto',
            field=models.TextField(default='Crie seu perfil profissional e destaque suas habilidades para empresas e oportunidades de estágio.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card1_titulo',
            field=models.CharField(default='Monte seu Perfil', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card2_texto',
            field=models.TextField(default='Entre em contato direto com empresas da região e participe de processos seletivos simplificados.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card2_titulo',
            field=models.CharField(default='Conecte-se às Empresas', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card3_texto',
            field=models.TextField(default='Acesse vagas de estágio, emprego e projetos de pesquisa disponíveis no LinkIF.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card3_titulo',
            field=models.CharField(default='Encontre Vagas', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card4_texto',
            field=models.TextField(default='Amplie sua experiência e fortaleça seu currículo através de oportunidades reais.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_card4_titulo',
            field=models.CharField(default='Cresça com o IFRN', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_cta_texto',
            field=models.TextField(default='Explore as oportunidades disponíveis e inicie sua trajetória profissional.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='estudante_cta_titulo',
            field=models.CharField(default='Pronto para dar o próximo passo?', max_length=150),
        ),
    ]
