# Generated by Django 5.2.7 on 2025-11-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0003_alter_vaga_data_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='estado',
        ),
        migrations.DeleteModel(
            name='AreaAtuacao',
        ),
    ]
