# Generated by Django 5.2.7 on 2025-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0003_vaga_etapa_alter_candidatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='etapa',
            field=models.CharField(choices=[('pendente_aprovacao', 'Pendente aprovação'), ('publicada', 'Publicada'), ('inscricoes_fechadas', 'Inscrições fechadas'), ('analise_curriculos', 'Análise de currículos'), ('entrevistas', 'Entrevistas'), ('finalizada', 'Finalizada')], default='pendente_aprovacao', max_length=30),
        ),
    ]
