# Generated by Django 5.2.7 on 2025-11-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0003_homecontent_estudante_card1_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudante', 'Para Estudantes'), ('empresa', 'Para Empresas')], default='estudante', max_length=20, verbose_name='Tipo de público')),
                ('icone', models.CharField(help_text='Exemplo: bi-person-circle, bi-building, bi-rocket-takeoff', max_length=50, verbose_name='Ícone Bootstrap')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features (Estudantes e Empresas)',
                'ordering': ['tipo', 'ordem'],
            },
        ),
    ]
