# Generated by Django 5.2.7 on 2025-12-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0004_alter_vaga_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['-data_publicacao', '-id'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AlterField(
            model_name='vaga',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='linkif.perfilformacao', verbose_name='Curso alvo'),
        ),
    ]
