# Generated by Django 5.2.8 on 2025-11-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0004_feature'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaatuacao',
            options={'ordering': ['nome'], 'verbose_name': 'Área de Atuação', 'verbose_name_plural': 'Áreas de Atuação'},
        ),
        migrations.AlterField(
            model_name='areaatuacao',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da área'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.coordenador', verbose_name='Aprovado por'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkif.areaatuacao', verbose_name='Área de atuação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(verbose_name='Descrição detalhada da vaga'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='usuarios.empresa', verbose_name='Empresa responsável'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='remuneracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneração (R$)'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo',
            field=models.CharField(choices=[('estagio', 'Estágio'), ('emprego', 'Emprego'), ('bolsa', 'Bolsa')], default='estagio', max_length=20, verbose_name='Tipo de vaga'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título da vaga'),
        ),
    ]
