# Generated by Django 5.2.7 on 2025-11-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0004_remove_vaga_area_remove_vaga_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilformacao',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='linkif.perfilformacao', verbose_name='Curso Alvo'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='perfilformacao',
            name='cor_titulo',
            field=models.CharField(blank=True, default='#1b1f5b', max_length=30, verbose_name='Cor do título (hex ou nome)'),
        ),
        migrations.AlterField(
            model_name='perfilformacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
