# Generated by Django 5.2.7 on 2025-12-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0005_alter_vaga_options_alter_vaga_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='assunto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
