# Generated by Django 5.2.8 on 2025-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0005_alter_areaatuacao_options_alter_areaatuacao_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
