# Generated by Django 5.2.7 on 2025-11-26 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0005_perfilformacao_descricao_curta_siteconfig_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['tipo', 'ordem'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Conteúdo da Home', 'verbose_name_plural': 'Conteúdos da Home'},
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card1_texto',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card1_titulo',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card2_texto',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card2_titulo',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card3_texto',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card3_titulo',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card4_texto',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_card4_titulo',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_cta_texto',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='estudante_cta_titulo',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='imagem_empresas',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='imagem_estudantes',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='texto_empresas',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='texto_estudantes',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='titulo_empresas',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='titulo_estudantes',
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icone',
            field=models.CharField(max_length=50, verbose_name='Ícone Bootstrap'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Para Estudantes'), ('empresa', 'Para Empresas')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='card1_texto',
            field=models.TextField(default='Um ambiente criado para centralizar oportunidades profissionais.'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='card2_texto',
            field=models.TextField(default='Aproxima estudantes e empresas.'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='card3_texto',
            field=models.TextField(default='Transforme formação técnica em experiência real.'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='subtitulo_banner',
            field=models.CharField(default='Seu futuro começa aqui.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='texto_sobre',
            field=models.TextField(default='O LinkIF conecta estudantes, ex-alunos e empresas.'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='titulo_banner',
            field=models.CharField(default='Da ideia à prática, do campus à carreira.', max_length=200),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='titulo_sobre',
            field=models.CharField(default='O que é o LinkIF?', max_length=100),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilformacao',
            name='cor_titulo',
            field=models.CharField(blank=True, default='#1b1f5b', max_length=30, verbose_name='Cor do título'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='descricao_curta',
            field=models.TextField(default='Conectando talentos técnicos do IFRN às melhores oportunidades profissionais.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email_contato',
            field=models.EmailField(default='contato@ifrn.edu.br', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='endereco',
            field=models.CharField(default='Av. Potengi, São Paulo do Potengi - RN', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='mapa_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='telefone',
            field=models.CharField(default='(84) 98888-8888', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL, verbose_name='Empresa responsável'),
        ),
    ]
