# Generated by Django 5.2.7 on 2025-12-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0006_mensagemcontato_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
