# Generated by Django 5.2.7 on 2025-12-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0006_alter_feature_options_alter_homecontent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='texto_sobre',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='titulo_sobre',
        ),
    ]
