# Generated by Django 5.2.7 on 2026-10-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0006_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
