# Generated by Django 5.2.7 on 2025-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkif', '0007_remove_homecontent_texto_sobre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='imagem_banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='subtitulo_banner',
            field=models.CharField(default='Aprender, se conectar e crescer: seu futuro começa aqui.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='titulo_banner',
            field=models.CharField(default='Da ideia à prática, do campus à carreira.', max_length=200),
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
