# Generated by Django 5.2.7 on 2025-11-05 00:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(help_text='Nome público da empresa (ex: Tech Solutions)', max_length=100, verbose_name='Nome da Empresa')),
                ('razao_social', models.CharField(help_text='Nome jurídico completo (ex: Tech Solutions LTDA)', max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Digite apenas números ou use o formato 00.000.000/0000-00', max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(help_text='Inclua o DDD (ex: (84) 99999-9999)', max_length=20, verbose_name='Telefone de Contato')),
                ('email', models.EmailField(help_text='Email institucional usado para login', max_length=254, unique=True, verbose_name='Email Corporativo')),
                ('site', models.URLField(blank=True, help_text='Opcional — ex: https://empresa.com.br', null=True, verbose_name='Site da Empresa')),
                ('descricao', models.TextField(blank=True, help_text='Fale brevemente sobre a atuação, missão ou área de interesse', null=True, verbose_name='Descrição da Empresa')),
                ('logradouro', models.CharField(help_text='Rua, avenida ou local onde a empresa está localizada', max_length=100, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Use a sigla — ex: RN', max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, help_text='Ex: 59000-000', max_length=10, verbose_name='CEP')),
                ('setor', models.CharField(blank=True, help_text='Ex: Tecnologia da Informação, Educação, Comércio...', max_length=80, null=True, verbose_name='Setor de Atuação')),
                ('tamanho_empresa', models.CharField(blank=True, choices=[('pequena', 'Pequena'), ('media', 'Média'), ('grande', 'Grande')], max_length=20, null=True, verbose_name='Porte da Empresa')),
                ('logo', models.ImageField(blank=True, help_text='Imagem em formato PNG ou JPG', null=True, upload_to='empresas/logos/', verbose_name='Logo da Empresa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('empresa', 'Empresa'), ('coordenador', 'Coordenação')], max_length=20, verbose_name='Tipo de usuário')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado pela coordenação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=100, verbose_name='Curso')),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Portfólio (opcional)')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor ou Departamento')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
    ]
