# Generated by Django 5.2.7 on 2025-12-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('acesso_aluno', 'Pode acessar a área do aluno'), ('acesso_empresa', 'Pode acessar a área da empresa'), ('acesso_coordenacao', 'Pode acessar a área da coordenação'), ('can_candidatar', 'Pode se candidatar a vagas'), ('can_explorar_alunos', 'Pode visualizar perfis de alunos'), ('can_post_vaga', 'Pode cadastrar vaga'), ('aluno_aprovado', 'Aluno aprovado pela coordenação'), ('empresa_aprovada', 'Empresa aprovada pela coordenação')]},
        ),
    ]
