# Generated by Django 5.2.7 on 2025-12-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('acesso_aluno', 'Pode acessar área de aluno'), ('acesso_empresa', 'Pode acessar área de empresa'), ('acesso_coordenacao', 'Pode acessar área da coordenação'), ('aluno_aprovado', 'Aluno aprovado pela coordenação'), ('empresa_aprovada', 'Empresa aprovada pela coordenação')]},
        ),
    ]
