# Generated by Django 5.2.7 on 2025-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto-aluno/'),
        ),
    ]
