# Generated by Django 5.2.8 on 2025-11-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto-empresa/'),
        ),
    ]
