# Generated by Django 5.2.7 on 2025-12-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('acesso_aluno', 'Pode acessar a área do aluno'), ('acesso_empresa', 'Pode acessar a área da empresa'), ('acesso_coordenacao', 'Pode acessar a área da coordenação'), ('can_candidatar', 'Pode se candidatar a vagas'), ('can_explorar_alunos', 'Pode visualizar perfis de alunos'), ('aluno_aprovado', 'Aluno aprovado pela coordenação'), ('empresa_aprovada', 'Empresa aprovada pela coordenação')]},
        ),
    ]
