# Generated by Django 5.2.7 on 2025-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_coordenador_usuario_remove_empresa_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
