"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
from django.contrib.messages import constants as messages

load_dotenv(find_dotenv())

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# Configurações de segurança
# ============================
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0']
BUILD_ENV = os.getenv("BUILD_ENV", default="local")

if os.getenv("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split()


# ============================
# Sistema de Mensagens
# ============================
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# ============================
# Aplicações instaladas
# ============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth_suap',
    
    # Apps do projeto
    'usuarios',
    'linkif',
    'dashboard',
    
    # Forms e filters
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
]


# ============================
# Site ID
# ============================
SITE_ID = 1

# Configurações do Crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ============================
# Middleware
# ============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


# ============================
# Configuração de Templates
# ============================
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # templates globais
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'linkif.context_processors.site_context',
                'linkif.context_processors.splash_screen_processor',
            ],
        },
    },
]


# ============================
# Aplicação WSGI
# ============================
WSGI_APPLICATION = 'config.wsgi.application'


# ============================
# Banco de Dados
# ============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# Validação de Senhas
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================
# Backends de Autenticação
# ============================
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# ============================
# Internacionalização
# ============================
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Fortaleza'
USE_I18N = True
USE_TZ = True


# ============================
# Arquivos Estáticos
# ============================
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ============================
# Upload de arquivos
# ============================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================
# Sistema de Email (Console)
# ============================
if BUILD_ENV == "production":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST")
    EMAIL_PORT = os.getenv("EMAIL_PORT")
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ============================
# Configuração do Usuário Customizado
# ============================
AUTH_USER_MODEL = "usuarios.Usuario"


# ============================
# Configurações Allauth
# ============================
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True

# Forms customizados:
# ACCOUNT_FORMS = {
#     "login": "usuarios.forms.UserLoginForm",
#     "reset_password": "usuarios.forms.UserResetPasswordForm", 
#     "reset_password_from_key": "usuarios.forms.UserResetPasswordKeyForm",
# }

# ============================
# Configurações Social Account
# ============================
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_ADAPTER = "usuarios.adapters.CustomSocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "suap": {
        "APP": {
            "client_id": os.getenv("SUAP_CLIENT_ID"),
            "secret": os.getenv("SUAP_CLIENT_SECRET"),
        },
        "SCOPE": [
            "identificacao", 
            "email",
        ]
    },
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
            "key": ""
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        }
    }
}

# ============================
# REDIRECIONAMENTOS
# ============================
LOGIN_REDIRECT_URL = "usuarios:redirecionar_dashboard"
LOGIN_URL = "usuarios:login"
LOGOUT_REDIRECT_URL = "linkif:index"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
