"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
from django.contrib.messages import constants as messages

load_dotenv(find_dotenv())

BASE_DIR = Path(__file__).resolve().parent.parent


# Segurança
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0']
BUILD_ENV = os.getenv("BUILD_ENV", default="local")

if os.getenv("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split()


# Aplicações instaladas
INSTALLED_APPS = [
    # Django nativo
    # Django nativo
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth_suap',
    
    # Apps do projeto
    'usuarios',
    'linkif',
    'dashboard',

    # Formulários

    # Formulários
    'crispy_forms',
    'crispy_bootstrap5',

    # Filtros

    # Filtros
    'django_filters',

    # Tabelas
    'django_tables2',

    # Tabelas
    'django_tables2',
]


# Site ID
SITE_ID = 1

# Configurações do Crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'usuarios.middleware.SocialLoginRedirectMiddleware',
]


# Configuração de templates
# Configuração de templates
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'linkif.context_processors.site_context',
                'dashboard.context_processors.splash_screen_processor',
                'dashboard.context_processors.splash_screen_processor',
            ],
        },
    },
]


# WSGI
# WSGI
WSGI_APPLICATION = 'config.wsgi.application'


# Banco de dados
# Banco de dados
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validação de senhas
# Validação de senhas
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
     'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Backends de autenticação
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Internacionalização
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Fortaleza'
USE_I18N = True
USE_TZ = True


# Arquivos estáticos
# Arquivos estáticos
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "static",
]



# Upload de arquivos
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Modelo de usuário customizado
# Modelo de usuário customizado
AUTH_USER_MODEL = "usuarios.Usuario"


# Configurações Allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # ou 'mandatory'


# Configurações Social Account
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_ADAPTER = "usuarios.adapters.CustomSocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "suap": {
        "APP": {
            "client_id": os.getenv("SUAP_CLIENT_ID"),
            "secret": os.getenv("SUAP_CLIENT_SECRET"),
        },
        "SCOPE": [
            "identificacao", 
            "email",
        ]
    },
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
            "key": ""
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        }
    }
}

# Redirecionamentos
LOGIN_REDIRECT_URL = "usuarios:redirecionar_dashboard"
LOGIN_URL = "usuarios:login"
LOGOUT_REDIRECT_URL = "linkif:index"

# Mensagens
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Email
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
