"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# Configurações de segurança
# ============================
SECRET_KEY = 'django-insecure-btew1yno23!9g=k79q%xp(^zgf!dpnu-0el5uwrfzi_exw0nde'
DEBUG = True
ALLOWED_HOSTS = []


# ============================
# Aplicações instaladas
# ============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # APPS DO SEU PROJETO
    'usuarios',
    'linkif',
    'dashboard',

    # Crispy Forms (Formulários Bonitos)
    'crispy_forms',
    'crispy_bootstrap5',
]

# Configurações do Crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ============================
# Middleware
# ============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================
# Configuração de Templates
# ============================
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # templates globais
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'linkif.context_processors.site_context',
            ],
        },
    },
]


# ============================
# Aplicação WSGI
# ============================
WSGI_APPLICATION = 'config.wsgi.application'


# ============================
# Banco de Dados
# ============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# Validação de Senhas
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# ============================
# Internacionalização
# ============================
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Fortaleza'
USE_I18N = True
USE_TZ = True


# ============================
# Arquivos Estáticos
# ============================
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",   # pasta /static/
]

# ============================
# Upload de arquivos
# ============================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================
# Sistema de Email (Console)
# ============================
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ============================
# Configuração do Usuário Customizado
# ============================
AUTH_USER_MODEL = "usuarios.Usuario"


# ============================
# REDIRECIONAMENTOS DE LOGIN E LOGOUT
# ============================

# para onde o usuário vai DEPOIS de fazer login
# AGORA ESTÁ CORRETO → vai usar sua view de redirecionamento
LOGIN_REDIRECT_URL = "dashboard:inicio"

# quando tenta acessar algo sem estar logado
LOGIN_URL = "usuarios:login"

# para onde vai após logout
LOGOUT_REDIRECT_URL = "index"


# ============================
# Primary Key padrão
# ============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
